In [2]:
import numpy as np

In [3]:
X = np.array([[1,1,-1],
              [1,0,-2],
              [1,2, 0],
              [1,1, 1]])

In [4]:
X

array([[ 1,  1, -1],
       [ 1,  0, -2],
       [ 1,  2,  0],
       [ 1,  1,  1]])

In [5]:
y = np.array([2,0,3,3])

In [6]:
y

array([2, 0, 3, 3])

In [7]:
xtx = np.dot(X.T,X)
xtx = X.T@X

In [8]:
xtx

array([[ 4,  4, -2],
       [ 4,  6,  0],
       [-2,  0,  6]])

In [15]:
np.dot(np.dot(np.linalg.inv(xtx),X.T),y)

array([1.5       , 0.83333333, 0.66666667])